# Generated by Django 5.2.8 on 2025-11-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En Preparacion'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
    ]
